### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by sinewalker** [sinewalker/sinewalker.github.io#9]
I want a light-text-on-dark-background theme.

I think I can just tweak the CSS to start with.

**Comment by sinewalker** [comment]
experiments with simple maniuplations with `files/assets/css/custom.css` go a long way.  Here's some simple stuff (the 100x100 pixel image is taken from the GitHub Dark Stylish theme -- I'd probably make my own to use)

``` css
body {
    background-color: #333;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAgMAAAANjH3HAAAACVBMVEUaGhohISElJSUh9lebAAAB20lEQVRIx4XWuZXDMAwE0C0SAQtggIIYoAAEU+aKOHhYojTrYP2+QfOW/5QIJOih/q8HwF/pb3EX+UPIveYcQGgEHiu9hI+ihEc5Jz5KBIlRRRaJ1JtoSAl5Hw96hLB1/up1tnIXOck5jZQy+3iU2hAOKSH1JvwxHsp+5TLF5MOl1/MQXsVs1miXc+KDbYydyMeUgpPQreZ7fWidbNhkXNJSeAhc6qHmHD8AYovunYyEACWEbyIhNeB9fRrH3hFi0bGPLuEW7xCNaohw1vAlS805nfsrTspclB/hVdoqusg53eH7FWot+wjYpOViX8KbFFKTwlnzvj65P9H/vD0/hibYBGhPwlPO8TmxRsaxsNnrUmUXpNhirlJMPr6Hqq9k5Xn/8iYQHYIuQsWFC6Z87IOxLxHphSY4SpuiU87xJnJr5axfeRd+lnMExXpEWPpuZ1v7qZdNBOjiHzDREHX5fs5Zz9p6X0vVKbKKchlSl5rv+3p//FJ/PYvoKryI8vs+2G9lzRmnEKkh+BU8yDk515jDj/HAswu7CCz6U/Mxb/PnC9N41ndpU4hUU7JGk/C9PmP/M2xZYdvBW2PObyf1IUiIzoHmHW9yTncliYs9A9tVNppdShfgQaTLMf+j3X723tLeHgAAAABJRU5ErkJggg==) !important;


    color: #aaa;
}

a {
    color: #e37f2a;
}

a:hover {
    color: #20b2d2;
    text-decoration: underline;
}

code {
    background-color: #111;
    color: #ccc !important;
}
```

 The ipython notebook CSS is much more complicated though:

``` css

div.text_cell_render {
    color: #aaa;
}

div.prompt.input_prompt {
    color: #222;
}
```

That's a start, but still the inline code is overridden by `nikola_ipython.css`.   [This blog](https://kmdouglass.github.io/stories/notes/nikola.html) might help.
